# -*- coding: utf-8 -*-
"""SVMHackathon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iJJQGR3dybVOD7xx818mI29FPEQMhD2c
"""
""" it is for address fetching."""
import pandas as pd
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="Aman")
def datas():
  Address=[]
  df=pd.read_csv('C:\Users\Hp\Desktop\finalproject\data.csv')
  lat=list(df['latitude'])
  lon=list(df['longitude'])
  for i in range (1):
    
    try:
        location = geolocator.reverse(str(lat[i])+","+str(lon[i]))
        Address.append(location.address)
    except:
        continue 
  
  return Address 
          
